### ISSUE TITLE
Add icon and text aligment to UIAlertAction button

### ISSUE THREAD

**Issue by ErAshu** [SintraWorks/ActionSheetController#2]
How can i add icon to Action button and set the text alignment to left on Action Button.

For reference, you can see the whatsApp. I need exactly to WhatsApp action sheet.

![whatsapp image 2017-11-19 at 2 02 15 am](https://user-images.githubusercontent.com/4178384/32984638-3b407e34-ccd0-11e7-9dbb-2a9c950f7997.jpeg)

**Comment by SintraWorks** [comment]
On 18 Nov 2017, at 21:51, Ashutosh Kumar <notifications@github.com> wrote:
> 
> How can i add icon to Action button and set the text alignment to left on Action Button.
> 
Hi Ashutosh,

I changed the view property on ActionsheetControllerAction to be public, and made it possible supply both a title and an icon.

You can henceforth access the action’s view after creating the action and adding it to a view controller. (Note: due to implementation details, it is obligatory to add the view to its controller before accessing the view’s contents.)

So, after creating the button and adding it to a controller, but before showing the action sheet, you can customise the action’s button as needed, for example:

	let action2 = ActionSheetControllerAction(…)

	…ensure action2 lives inside a controller…

        if let action2Button = action2.view as? UIButton {
            action2Button.contentHorizontalAlignment = .left
            action2Button.contentEdgeInsets = UIEdgeInsets(top: 0, left: 15, bottom: 0, right: 15)
        }

To see its use in code, pull from the repo, and have a look at TableViewDelegate.swift. In the groupedActionsSheet function we now obtain the view for action4 (which is a button), and customise it (lines 152-156).

I also adjusted the action view initialisation to no longer default to labelling the button “Untitled” if no title is supplied.

Kind regards,
António Nunes
SintraWorks
